### ISSUE TITLE
In SOURCE, when there are no `modifications`, do not show semicolon

### ISSUE THREAD

**Issue by ronaldtse** [geolexica/geolexica-server#181]
https://isotc204.geolexica.org/concepts/3.1.5.2/

<img width="753" alt="Screen Shot 2022-08-11 at 9 41 17 AM" src="https://user-images.githubusercontent.com/11865/184050911-91ac9f43-0d8f-4d2b-acbb-de81c89baf7c.png">

**Comment by HassanAkbar** [comment]
@ronaldtse I have opened a [PR](https://github.com/geolexica/geolexica-server/pull/183) to remove the `;`. But the `;` is to separate multiple `sources` and not for separating `modification`. Currently we are not showing modification from the concepts if it is a key in `.yaml` file, `modification` will only be shown if it is with the clause e.g

**will not show the modification**
```yaml
- type: authoritative
    origin:
      ref: ISO/TS 14812:2022
      clause: 3.1.1.1
      link: https://www.iso.org/standard/79779.html
    modification: "some modification"
```

**will show the modification**
```yaml
- type: authoritative
    origin:
      ref: ISO/TS 14812:2022
      clause: 3.1.1.1, modified - some modification
      link: https://www.iso.org/standard/79779.html
```
