### ISSUE TITLE
Copyright on 404 pages

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#44]
Copyright pages are somewhat unique. They feature a pretty large copyright section, which is not present on any other page, not even on About page. Quite odd, isn't it?

This is how it looks like in case of TC211 site:

> ![Zrzut ekranu 2020-04-18 o 15 05 29](https://user-images.githubusercontent.com/154287/79638610-b590fc00-8186-11ea-91b3-5054ed65f743.png)

Green frames were added by me, as they mark yet another oddity. Information within these frames require a significant amount of configuration in `_config.yml`, which is used only on that page. Quite much, given the little importance of 404 page.

For instance, in case of TC211 site:

```yaml
org:
  name: International Organization for Standardization
  website:
    url: https://www.iso.org/
    title: www.iso.org
  email: copyright@iso.org
  address: |-
    Chemin de Blandonnet 8
    CP 401
    1214 Vernier, Geneva
    Switzerland
```

My opinion is that:

1. Copyright details should be presented elsewhere. Either on a separate Copyright page, which does not exist now, or as a section on About page.

2. 404 page should not require that much configuration. If these `org` entries will be used elsewhere, then it's okay to re-use them on 404 page. But if not, then a simple link to Copyright page or About page will be better.

cc @ronaldtse @strogonoff
