### ISSUE TITLE
Term's normative status (formerly classification) is not localized

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#56]
We need to find a way of displaying term's (designation's) **normative status** (formerly **classification**) in a localized way, taking into account that there may be more than one term per language.

This is best illustrated on https://isotc211-staging.geolexica.org/concepts/150 of TC211 glossary, which is defined as follows (some entries removed for clarity):

```yaml
---
term: ellipsoidal height
termid: 150
eng:
  id: 150
  term: ellipsoidal height
  language_code: eng
  classification: preferred
rus:
  id: 150
  term: эллипсоидальная высота
  language_code: rus
  classification: admitted
```

Rendered HTML is as follows (again, some elements removed):

```yaml
<article
  class="localized-term field lang-eng status-valid classification-preferred"
  id="entry-lang-eng">

  <p class="field-name">eng</p>

  <div class="field-value">    
      <h3 class="localized">ellipsoidal height</h3>
  </div>
</article>

<article
  class="localized-term field lang-rus status-valid classification-preferred"
  id="entry-lang-rus">

  <p class="field-name">rus</p>

  <div class="field-value">
      <h3 class="localized">эллипсоидальная высота</h3>
  </div>
</article>

<section class="field info">
  <p class="field-name">info</p>
  <div class="field-value">
    <ul class="labels">
      <li>status: valid</li>
      <li>classification: preferred</li>
      <li>date accepted: 2003-02-15</li>
    </ul>
  </div>
</section>
```

Problems:

- Both article elements have `classification-preferred` CSS class, even though it is incorrect for Russian term.
- Info section which summarizes the concept states `classification: preferred`, even though it is not true for some localized concepts.

Also RDFs are broken. However they will undergo overhaul anyway, and the way forward has been discussed already. Indeed this issue was addressed in format described in #2, also what to do with the new data models has been already discussed. Hence, this issue is related to HTMLs only.

NOTE: iev-demo site is affected by this issue as well.
