### ISSUE TITLE
Duplicated output formats configuration

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#69]
In `_config.yml`, both:

```yaml
collections:
  concepts:
    output: true
  concepts_json:
    output: true
    output_ext: .json
  concepts_jsonld:
    output: true
    output_ext: .jsonld
  concepts_ttl:
    output: true
    output_ext: .ttl
  concepts_tbx:
    output: true
    output_ext: .tbx.xml
  concepts_yaml:
    output: true
    output_ext: .yaml
```

and:

```
geolexica:
  formats:
    - html
    - json
    - json-ld
    - turtle
    - yaml
```

probably serve the same purpose, that is defining which concept formats should be rendered and which should not. This should be cleaned-up. Personally, I prefer the latter for conciseness, but on the other hand the former may be easier in Jekyll and perhaps it can be used to configure more things.

Something to think about.
