### ISSUE TITLE
Description and Tagline inconsistency

### ISSUE THREAD

**Issue by skalee** [geolexica/geolexica-server#86]
Clarification is needed.

### TC211 site

TC211 Geolexica config has both `tagline` and `description` defined as follows:

```yaml
tagline: >-
  The authoritative
  geographic information terminology database

description: >-
  The authoritative glossary for geographic information technology from ISO/TC 211.
```

Tagline is unused whereas description is used on all pages as the last dash-separated segment in `<title>` HTML element. For example, on `/index.html` page:

```html
<title>
Index — The authoritative glossary for geographic information technology from ISO/TC 211.
</title>
```

### IEV site

IEV config also has both `tagline` and `description` defined as follows:

```yaml
tagline: "Electropedia: The World's Online Electrotechnical Vocabulary"

description: >-
  Electropedia is produced by the IEC, the world’s leading organization that prepares and publishes International Standards for all electrical, electronic and related technologies – collectively known as “electrotechnology”. Electropedia (also known as the "IEV Online") contains all the terms and definitions in the International Electrotechnical Vocabulary or IEV which is published also as a set of publications in the IEC 60050 series that can be ordered separately from the IEC webstore.
```

Their usage is different though. Tagline is used in `<title>` elements whereas description is used in `<meta name="description">` elements.

### Which one is correct?

Existence of 9d280ce998c0aebea5f93025745284ed523bd64f commit (for IEV site only) suggests that the IEV is correct whereas TC211 is buggy. Nevertheless, I need confirmation.
